services:
  sisop:
    tty: true
    
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: sincro

    volumes:
      - type: bind
        source: .
        target: /home/sisop